name: iFrameFormRequest
author: astolwijk
current: 1.3.0
category: Request
tags: [Request,iFrame,upload,files,AJAX]
demo: http://www.aryweb.nl/projects/iFrameFormRequest/Docs/

sources:
  - "Source/iFrameFormRequest.js"
